name: app
description: "A new Flutter project."
#test
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Used to inject dependencies
  get_it: ^7.7.0

  # Used to check the Internet connection
  internet_connection_checker_plus: ^2.3.0

  # Used for state management
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

  # Used as Api Clint
  dio: ^5.4.3+1

  # used to procedural programming
  dartz: ^0.10.1

  # used to compare objects
  equatable: ^2.0.4

  # Used to display messages on the screen
  fluttertoast: ^8.2.5

  # User as Simple Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Used for attractive and interactive window displays
  awesome_dialog: ^3.2.1

  # Used to store and retrive small values
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # This command generates the object adapter in the Hive DB :
  # Commend =>  flutter packages pub run build_runner build
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true


  assets:
      - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
